version: '3.9'

services:

  javamongo.service:
  
    container_name: javamongo.service
    hostname: javamongo.service
    # image: "brawijayahospital/appointment:0.0.1"
    image: "java-mongo:1.0.0"
    restart: always
    environment:
      - "JVM_OPTIONS=-Dspring.config.location=/opt/app/application.properties"
    ports: 
      - "8082:8080"
    volumes:
      - "./application.properties:/opt/app/application.properties"
    privileged: true

networks:
  default:
    external: true
    name: mongo_net